# Generated by Django 4.1.6 on 2023-03-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jspet", "0002_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="health",
            field=models.IntegerField(default=10),
        ),
    ]
