# Generated by Django 4.1.6 on 2023-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jspet", "0003_alter_pet_health"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="health",
            new_name="happiness",
        ),
        migrations.AddField(
            model_name="pet",
            name="hunger",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="pet",
            name="thirst",
            field=models.IntegerField(default=10),
        ),
    ]
