# Generated by Django 4.1.6 on 2023-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jspet", "0004_rename_health_pet_happiness_pet_hunger_pet_thirst"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="birth_date",
            field=models.DateTimeField(auto_now_add=True, default='2023-03-16T14:53:26.764Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pet",
            name="last_save",
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
