# Generated by Django 4.1.6 on 2023-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jspet", "0005_pet_birth_date_pet_last_save"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="hunger",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pet",
            name="thirst",
            field=models.IntegerField(default=0),
        ),
    ]
